export const USERS_ACTIONS = {
  REQUEST_START: 'REQUEST_START',
  REQUEST_FAILURE: 'Request_Failure',
  REQUEST_SUCCESS_GET: 'REQUEST_SUCCESS_GET',
  REQUEST_SUCCESS_DELETE: 'REQUEST_SUCCESS_DELETE',
};
